### ISSUE TITLE
paste ip problem in firefox 

### ISSUE THREAD

**Issue by parisasafari** [CautemocSg/ng-ip-address#2]
I used ng-ip-address and  i have a problem in firefox,  i cant paste(ctrl+v) any ip address , but it works fine in chrome .
whould anybody have an idea to help me ?

**Comment by CautemocSg** [comment]
Yep, confirmed that's a bug. The problem is with the character codes I am preventing the default behavior of. Most likely the fix will be to simply add the needed codes to the check. A work-around is to use your mouse to paste (right-click -> paste) instead of Ctrl + V. I will fix this issue when I have time, which will likely be this weekend. Thanks.

**Comment by CautemocSg** [comment]
Resolved in version 1.1.11
